packages:
  - studio
allowBuilds:
  esbuild: true
  unrs-resolver: true
  sharp: true
  '@sentry/cli': true
minimumReleaseAgeExclude:
  - '@sentry/browser-utils@10.75.1'
  - '@sentry/browser@10.75.1'
  - '@sentry/core@10.75.1'
  - '@sentry/feedback@10.75.1'
  - '@sentry/nextjs@10.75.1'
  - '@sentry/node-core@10.75.1'
  - '@sentry/node@10.75.1'
  - '@sentry/opentelemetry@10.75.1'
  - '@sentry/react@10.75.1'
  - '@sentry/replay-canvas@10.75.1'
  - '@sentry/replay@10.75.1'
  - '@sentry/server-utils@10.75.1'
  - '@sentry/vercel-edge@10.75.1'
